markdown: kramdown
plugins:
  - github-pages
remote_theme: rakutentech/android-buildconfig@gh-pages-theme

title: Mini App SDK for JS
description: Provide avenues to consume extended features in mini apps.
repository: rakutentech/js-miniapps

docs_path: docs
api_docs_path: api

collections:
  versions: