version: 2

## Empty config file to prevent CircleCI from running when commits are pushed to gh-pages branch
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          command: echo ""

workflows:
  version: 2

  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
